config/routes.rb
Rails.application.routes.draw do
  root 'messages#index'
  get '/messages' => 'messages#index'
  get 'messages/new' => 'messages#new'
  post 'messages' => 'messages#create'
  
  resources :messages
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @messages = Message.all
  end

  def new 
    @message = Message.new 
  end 

  def show
    @message = Message.find(params[:id])
  end

  def create 
    @message = Message.new(message_params) 
    if @message.save 
      redirect_to '/messages' 
    else 
      render 'new' 
    end 
  end 

  def destroy
        @message = Message.find(params[:id])
        @message.destroy

        redirect_to messages_path
  end

  private 
  def message_params 
    params.require(:message).permit(:content) 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessengerApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="header">
      <div class="container">
        <img src="https://content.codecademy.com/courses/learn-rails/img/logo-1m.svg">
        <h1>Messenger</h1>
      </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/messages/create.html.erb
<h1>Messages#create</h1>
<p>Find me in app/views/messages/create.html.erb</p>

app/views/messages/index.html.erb
<div class="messages">
  <div class="container">
  	<% @messages.each do |message| %> 
			<div class="message"> 
  			<p class="content"><%= message.content %></p> 
  			<p class="time"><%= message.created_at %></p> 
        <%= link_to 'Read more ...', message_path(message)%>
			</div> 
		<% end %>
    <%= link_to 'New Message', "messages/new" %> 
  </div>
</div>

app/views/messages/new.html.erb
<div class="create">
  <div class="container">
    
    <!-- Your code here -->
    <%= form_for(@message) do |f| %>  
        <div class="field"> 
              <%= f.label :message %><br> 
              <%= f.text_area :content %> 
         </div> 
         <div class="actions"> 
              <%= f.submit "Create" %> 
              </div> 
        <% end %> 
  </div>
</div>

app/views/messages/show.html.erb
<div class="header">
  <div class="container">
    <img src="https://content.codecademy.com/courses/learn-rails/img/logo-1m.svg">
    <h1>Messenger</h1>
  </div>
</div>

<div class="messages">
  <div class="container">
			<div class="message"> 
  			<p class="content"><%= @message.content %></p> 
  			<p class="time"><%= @message.created_at %></p> 
            <%= link_to 'Delete Message', message_path(@message), method: :delete %> 
	</div> 
  </div>
</div>